background #111111
foreground #FFFFFF

background_opacity 0.6
confirm_os_window_close 0

cursor #FF3B30
selection_background #1F1F1F
selection_foreground #FFFFFF

color0  #111111
color1  #FF3B30
color2  #EAEAEA
color3  #CCCCCC
color4  #FFFFFF
color5  #B0B0B0
color6  #FF3B30
color7  #F5F5F5

color8  #2A2A2A
color9  #FF5F57
color10 #FFFFFF
color11 #D9D9D9
color12 #FFFFFF
color13 #C0C0C0
color14 #FF7A70
color15 #FFFFFF
