exec-once = awww-daemon
exec-once = waybar -c /home/ciro/.config/waybar/config.jsonc -s /home/ciro/.config/themes/current/waybar.css &
exec-once = swaync
exec-once = gnome-keyring-daemon --start --components=secrets