decoration {
    rounding = 0
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = false
    }

    blur {
        enabled = yes
	size = 7
        passes = 3
	ignore_opacity = true

	noise = 0.08
	contrast = 1.5

        new_optimizations = true
        xray = false
    	
    }
}
