input {
    kb_layout = latam,us

    follow_mouse = 1
    sensitivity = 0

    kb_options = grp:win_space_toggle

    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
