windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

layerrule {
    name = swaync_blur_center
    blur = on
    ignore_alpha = 0.3
    match:namespace = swaync-control-center
}

layerrule {
    name = swaync_blur_notifications
    blur = on
    ignore_alpha = 0.3
    match:namespace = swaync-notification-window
}

layerrule {
    name = swaync_animation
    animation = slide right
    match:namespace = swaync-control-center
}