background #1E1E2E
foreground #CDD6F4

background_opacity 0.6
confirm_os_window_close 0

cursor #89DCEB
selection_background #313244
selection_foreground #CDD6F4

color0  #1E1E2E
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #CBA6F7
color6  #89DCEB
color7  #CDD6F4

color8  #45475A
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #CBA6F7
color14 #89DCEB
color15 #FFFFFF