# variables
$terminal = kitty
$fileManager = nautilus
$menu = fuzzel
$mainMod = SUPER

# source files
source = ~/.config/hypr/extensions/monitor.conf
source = ~/.config/hypr/extensions/autostart.conf
source = ~/.config/hypr/extensions/environment.conf
source = ~/.config/hypr/extensions/input.conf
source = ~/.config/hypr/extensions/general.conf
source = ~/.config/hypr/extensions/decoration.conf
source = ~/.config/hypr/extensions/animations.conf
source = ~/.config/hypr/extensions/layouts.conf
source = ~/.config/hypr/extensions/binds.conf
source = ~/.config/hypr/extensions/windowrules.conf